# coding: utf-8

"""
    Kappa-framework user microservices

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List
from typing import Optional, Set
from typing_extensions import Self

class ConfigurationDetails(BaseModel):
    """
    ConfigurationDetails
    """ # noqa: E501
    tag: StrictStr
    info: StrictStr
    config_id: StrictInt = Field(alias="configId")
    config_interp: StrictStr = Field(alias="configInterp")
    display_value: StrictStr = Field(alias="displayValue")
    id: StrictInt
    tag_status: StrictInt = Field(alias="tagStatus")
    created_on: datetime = Field(alias="createdOn")
    modified_on: datetime = Field(alias="modifiedOn")
    __properties: ClassVar[List[str]] = ["tag", "info", "configId", "configInterp", "displayValue", "id", "tagStatus", "createdOn", "modifiedOn"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ConfigurationDetails from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ConfigurationDetails from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "tag": obj.get("tag"),
            "info": obj.get("info"),
            "configId": obj.get("configId"),
            "configInterp": obj.get("configInterp"),
            "displayValue": obj.get("displayValue"),
            "id": obj.get("id"),
            "tagStatus": obj.get("tagStatus"),
            "createdOn": obj.get("createdOn"),
            "modifiedOn": obj.get("modifiedOn")
        })
        return _obj


